xcpretty/xcpretty

features/simple_format.feature
features/steps/formatting_steps.rb
features/support/env.rb
features/test_format.feature
lib/xcpretty/formatters/formatter.rb
lib/xcpretty/formatters/rspec.rb
lib/xcpretty/formatters/simple.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/formatters/simple_spec.rb
spec/xcpretty/parser_spec.rb

Support output from `XCTestCase.measureBlock()` as following notated image:
[![screenshot 2015-02-07 20 45 14](https://cloud.githubusercontent.com/assets/33430/6092021/0af251ce-af0c-11e4-8ee4-c9f766b0ec0e.png)](https://travis-ci.org/norio-nomura/Base32/builds/49848814)

Add measuring support

---

lib/xcpretty/formatters/formatter.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

As discussed in #127 reopening going against master.

Parse write-file and Write auxiliary files

---

lib/xcpretty/printer.rb

This makes the output update more smoothly :)

Fix buffering issues with xcpretty.

---

lib/xcpretty/formatters/formatter.rb
lib/xcpretty/formatters/simple.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/formatters/simple_spec.rb
spec/xcpretty/parser_spec.rb

When xcodebuild is run with `RUN_CLANG_STATIC_ANALYZER=YES` it outputs `=== ANALYZE TARGET` instead of `=== BUILD TARGET`. It is still actually building the target.

Improve build target matcher

---

lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

Fixes https://github.com/supermarin/xcpretty/issues/152
This will change the output on a Bitcode failure from 
```
⌦  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```
to
```
⌦  ld: '/Users/felixkrause/Developer/Moto Deals/Pods/GoogleAnalytics-iOS-SDK/libGoogleAnalyticsServices.a(TAGHit.o)' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture armv7
⌦  clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Fixed not showing ld error messages

---

features/steps/formatting_steps.rb
lib/xcpretty/formatters/formatter.rb
spec/xcpretty/formatters/formatter_spec.rb

I always thought that the `⌦` symbol was a glitch rather than the expected symbol for errors.

Use the CROSS MARK (U+274C) symbol for errors

---

features/simple_format.feature
features/steps/formatting_steps.rb
lib/xcpretty/formatters/formatter.rb
lib/xcpretty/formatters/simple.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/formatters/simple_spec.rb
spec/xcpretty/parser_spec.rb
xcpretty.gemspec

Fixes #166 
Split off from #118, formats build/test/clean succeeded messages. Does not handle failure, since that prints to stderr anyway.

Format phase success

---

Rakefile
lib/xcpretty/reporters/html.rb
lib/xcpretty/syntax.rb
spec/xcpretty/syntax_spec.rb
xcpretty.gemspec

This removes a dependency on a Python project, and greatly improves syntax highlighting along with fixing #138.
Before:
After:
This does add a required dependency which may not be desired, if that is the case I'm happy to amend this pull request to make rouge optional.

Use rouge for highlighting instead of Pygments

---

lib/xcpretty/formatters/formatter.rb

Since commit 77e7091, the format_ld_warning method has been introduced without its default implementation (added now).

Add format_ld_warning default implementation

---

features/json_compilation_database_report.feature
features/steps/json_steps.rb
lib/xcpretty/reporters/json_compilation_database.rb

If no .pch file is processed before compiling a .c file, the JSON
compilation database formatter would replace `-include` directives using
empty paths. This casues tools like OCLint to fail when building those
files.

Fixes #193 - avoid setting include directives to empty paths

---

lib/xcpretty/parser.rb

PHASE_SCRIPT_EXECUTION_MATCHER was expecting an extra "/" at the end of its match.  This was preventing successful matches, causing the "Run Script" phase to not be shown. This fixes issue 163 (https://github.com/supermarin/xcpretty/issues/163)

Fixing PhaseScriptExecution regex

---

lib/xcpretty/reporters/junit.rb
spec/xcpretty/reporters/junit_spec.rb

The junit reporter doesn't assign a name to the root node of the xml
document. As such, on systems like jenkins a confusing label of '(root)' is
displayed when viewing test results. This commit changes that to use the
name provided by format_test_run_started.

Add name attribute to root node in junit reporter.

---

bin/xcpretty
lib/xcpretty/formatters/formatter.rb
lib/xcpretty/printer.rb

I was trying to write a formatter that outputs in JSON format, but needed to know the end of the parsing.

Formatter.finish: give formatters the ability to know the end

---

lib/xcpretty/reporters/html.rb
lib/xcpretty/syntax.rb

The wrong formatter was being used for HTML output, leading to ANSI escape codes being inserted.
Fixes this issue #195

Fixed issue where the wrong syntax formatter was being used for HTML

---

features/simple_format.feature
features/steps/formatting_steps.rb
lib/xcpretty/formatters/formatter.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/formatters/formatter_spec.rb
spec/xcpretty/parser_spec.rb

This will handle 'TargetName will not be code signed because ...' warnings and display them like this:

Handle 'TargetName will not be code signed because' warning

---

lib/xcpretty/parser.rb

Projects may decide to use their own compiler toolchain for building,
in which case the path to the clang executable will likely not contain
the /usr prefix. This commit thus removes that prefix from the
corresponding matcher.

Add support for custom compiler toolchains

---

features/simple_format.feature
features/steps/formatting_steps.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

Example of the error:
```
Check dependencies
No profile matching 'TargetName' found:  Xcode couldn't find a profile matching 'TargetName'. Install the profile (by dragging and dropping it onto Xcode's dock item) or select a different one in the General tab of the target editor.
Code signing is required for product type 'WatchKit App' in SDK 'iOS 10.2'
```

Add matcher for 'No profile matching 'TargetName' found:' dependency error

---

lib/xcpretty/reporters/html.rb

Improve screenshot matching for Test Suites that include namespaces, such as those written in Swift.
KIF screenshots only contain the name of the file, but xcpretty's test name for Swift tests contains the namespace which fails to match any screenshot.

Improve Screenshot Matching

---

lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

Upon a missing Provisioning profile/Code sign identity, the following errors are thrown (using Xcode 8):
missing Provisioning profile:
```
MyProject requires a provisioning profile. Select a provisioning profile for the "Debug" build configuration in the project editor.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
```
missing Code sign identity:
```
No certificate matching 'iPhone Distribution: Name (XXXXXXXXXX)' for team 'XXXXXXXXXX':  Select a different signing certificate for CODE_SIGN_IDENTITY, a team that matches your selected certificate, or switch to automatic provisioning.
Code signing is required for product type 'Application' in SDK 'iOS 10.0'
Code signing is required for …
```

Improve Code sign error checking

---

xcpretty.gemspec

closes #276 
I upgraded rouge to latest version.
All checks seem to be passed.
```
$ bundle exec rake spec
$ bundle exec rake cucumber
$ bundle exec rake lint
```

Upgrade rouge

---

lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

This addresses #282 by adding another matcher for errors formatted like:
`<module-includes>:1:1: error: umbrella header for module 'ModuleName' does not include header 'Header.h'`
Corresponding spec added as well. 
I'm not sure if this should be it's own matcher or if one of the other matchers should be extended to include this case, please let me know if I should update this.

Add support for <module-includes> errors

---

spec/xcpretty/reporters/junit_spec.rb

Sometimes the tests fail because of this missing require

Add missing rexml require

---

.rubocop.yml
lib/xcpretty/formatters/format_methods.rb
lib/xcpretty/formatters/simple.rb
lib/xcpretty/parser/chunks.rb
lib/xcpretty/parser/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

This message is printed when reading xcent files. It has an arbitrary
length depending on your entitlements. This currently has one issue
where it prints a newline after itself, because it exits on a specific
string after matching as many lines as possible between the start, and
there's no way to capture output after exiting.

Handle ProcessProductPackaging message

---

lib/xcpretty/formatters/format_methods.rb

This takes one argument so if formatters don't implement it, xcpretty
crashes

Fix universal binary template

---

lib/xcpretty/formatters/formatter.rb
lib/xcpretty/parser.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

This adds `format_other` to allow you to override behavior in a custom formatter for things that the current parser doesn't know how to match.

Add catch-all formatter

---

lib/xcpretty/parser/chunks.rb
spec/fixtures/constants.rb
spec/xcpretty/parser_spec.rb

Previously this regex required it end with `-Simulated`, that was never
the intention. Just making this non-capturing group optional doesn't
work and PATH ends up capturing the whole thing.

Fix ProcessProductPackaging for device

---

lib/xcpretty/parser.rb

Fixes #391.
Introduced by 16a96b71 in #313.
<h2 id="testing-steps">Testing steps</h2>
- Add
```ruby
gem 'xcpretty', git: 'https://github.com/revolter/xcpretty', branch: 'fix/uninitialized-constant-erb'
```
to your `Gemfile`.
- Run
```sh
bundle install
```

Fix uninitialized constant XCPretty::Parser::ERB crash
